  version: "3"
  services:
    userManagementMs:
      image: usermanagementmsimage
      ports:
        - "8081:8081"
      networks:
        - user-mysql
      depends_on:
        usermgmtsqldb:
          condition: service_healthy
    usermgmtsqldb:
      image: mysql:8
      networks:
        - user-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=usermgmtdb
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping","-h","localhost"]
        timeout: 20s
        retries: 10
  networks:
    user-mysql: